default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: 1234
  database: budgetapp_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: search_analytcis_development

test:
  <<: *default
  database: search_analytcis_test

production:
  <<: *default
  database: search_analytcis_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>